### ISSUE TITLE
Resolution doesnt come back to original

### ISSUE THREAD

**Issue by lucianomunoz** [GaoShanPictures/GAOLIB#5]
When I create a pose or a selection set, gaolib sets the resolution to 200x200 to create the thumbnails but after the process is finished it doesnt go back to the original resolution of my scene,

**Comment by GaoShanPictures** [comment]
Hi Luciano ! When creating a new item in the library, each time you click the Camera button, you need to click it again, even if you want to cancel the creation of an item. 

Clicking the first time on the camera button will set the render resolution and path so that the preview is Gaolib compatible, and the second time, when you hit the button (that now has text in it), it will set the render settings back as they were originally. 

If you abort after hitting the camera button just once, the settings will never go back to what they were.  I guess it's not ideal but so is the 3 clicks process to create an item.. One day I'm sure I'll find a way to do better ;) 

Happy Blending ! 
Anne

**Comment by lucianomunoz** [comment]
Hey Anne!

you're correct , i was missing clicking the camera button again!, couldn't that be done when I press the save pose button ? in the gaolib window at least? seems like one click too many.

Either way, thanks this is great

**Comment by GaoShanPictures** [comment]
I'll note that as a new improvement to add to the tool, I really need to get into this three steps item creation. 
I close this issue now .

Thanks for the feedback ! 

Anne

**Comment by freen75** [comment]
Hi Luciano,
This is exactly the issue we were just discussing on the Pataz channel: it's to do with the context problems inherent in Blender operators. We know about it, we want to fix it, but right now we don't have the time or the knowledge to do that. 
Any *constructive* advice on this issue would be welcomed.
